// <auto-generated />
using System;
using DocumentQA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentQA.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DocumentQA.Domain.Identity.Tenant", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("Tenants");
        });

        modelBuilder.Entity("DocumentQA.Domain.Identity.User", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<string>("Role").IsRequired().HasColumnType("text");
            b.Property<Guid?>("TenantId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("TenantId");
            b.ToTable("Users");
        });

        modelBuilder.Entity("DocumentQA.Domain.Identity.UsageLog", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<string>("ApiKey").IsRequired().HasColumnType("text");
            b.Property<bool>("CacheHit").HasColumnType("boolean");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<decimal>("CostUsd").HasColumnType("numeric");
            b.Property<bool>("FallbackUsed").HasColumnType("boolean");
            b.Property<int>("InputTokens").HasColumnType("integer");
            b.Property<int>("LatencyMs").HasColumnType("integer");
            b.Property<string>("Model").IsRequired().HasColumnType("text");
            b.Property<int>("OutputTokens").HasColumnType("integer");
            b.Property<string>("RequestId").IsRequired().HasColumnType("text");
            b.Property<string>("TenantId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<int?>("TtftMs").HasColumnType("integer");
            b.Property<Guid?>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("CreatedAt");
            b.HasIndex("TenantId");
            b.HasIndex(new[] { "TenantId", "CreatedAt" });
            b.ToTable("UsageLogs");
        });

        modelBuilder.Entity("DocumentQA.Domain.Identity.User", b =>
        {
            b.HasOne("DocumentQA.Domain.Identity.Tenant", "Tenant")
             .WithMany("Users")
             .HasForeignKey("TenantId")
             .OnDelete(DeleteBehavior.Cascade);
            b.Navigation("Tenant");
        });

        modelBuilder.Entity("DocumentQA.Domain.Identity.Tenant", b =>
        {
            b.Navigation("Users");
        });
#pragma warning restore 612, 618
    }
}
