using DocumentQA.Application.Abstractions.Identity;
using DocumentQA.Domain.Identity;
using DocumentQA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace DocumentQA.Api.Services;

public static class AdminSeeder
{
    private static async Task EnsureSchemaAsync(AppDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Tenants" (
                "Id"        uuid                        NOT NULL,
                "Name"      character varying(200)      NOT NULL,
                "Slug"      character varying(100)      NOT NULL,
                "IsActive"  boolean                     NOT NULL DEFAULT true,
                "CreatedAt" timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tenants_Slug" ON "Tenants" ("Slug");

            CREATE TABLE IF NOT EXISTS "Users" (
                "Id"           uuid                        NOT NULL,
                "TenantId"     uuid,
                "Email"        character varying(320)      NOT NULL,
                "PasswordHash" text                        NOT NULL,
                "Role"         text                        NOT NULL,
                "DisplayName"  character varying(200)      NOT NULL,
                "IsActive"     boolean                     NOT NULL DEFAULT true,
                "CreatedAt"    timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Users_Tenants_TenantId"
                    FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"    ON "Users" ("Email");
            CREATE        INDEX IF NOT EXISTS "IX_Users_TenantId" ON "Users" ("TenantId");

            CREATE TABLE IF NOT EXISTS "UsageLogs" (
                "Id"           bigint GENERATED BY DEFAULT AS IDENTITY,
                "RequestId"    text                        NOT NULL,
                "ApiKey"       text                        NOT NULL,
                "TenantId"     character varying(100)      NOT NULL DEFAULT 'public',
                "UserId"       uuid,
                "Model"        text                        NOT NULL,
                "InputTokens"  integer                     NOT NULL,
                "OutputTokens" integer                     NOT NULL,
                "CostUsd"      numeric                     NOT NULL,
                "LatencyMs"    integer                     NOT NULL,
                "TtftMs"       integer,
                "CacheHit"     boolean                     NOT NULL,
                "FallbackUsed" boolean                     NOT NULL,
                "CreatedAt"    timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_UsageLogs" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_UsageLogs_TenantId"           ON "UsageLogs" ("TenantId");
            CREATE INDEX IF NOT EXISTS "IX_UsageLogs_CreatedAt"           ON "UsageLogs" ("CreatedAt");
            CREATE INDEX IF NOT EXISTS "IX_UsageLogs_TenantId_CreatedAt"  ON "UsageLogs" ("TenantId", "CreatedAt");

            ALTER TABLE "Tenants" ADD COLUMN IF NOT EXISTS "DailyTokenLimit" integer NOT NULL DEFAULT 0;

            CREATE TABLE IF NOT EXISTS "ChatSessions" (
                "Id"               uuid                        NOT NULL,
                "TenantId"         character varying(100)      NOT NULL,
                "UserId"           uuid                        NOT NULL,
                "Title"            text                        NOT NULL DEFAULT 'New chat',
                "IncludeSharedDocs" boolean                    NOT NULL DEFAULT true,
                "CreatedAt"        timestamp with time zone    NOT NULL,
                "UpdatedAt"        timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_ChatSessions" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_ChatSessions_TenantId_UserId" ON "ChatSessions" ("TenantId", "UserId");

            CREATE TABLE IF NOT EXISTS "ChatMessages" (
                "Id"           uuid                        NOT NULL,
                "SessionId"    uuid                        NOT NULL,
                "Role"         text                        NOT NULL,
                "Content"      text                        NOT NULL,
                "SourcesJson"  text,
                "InputTokens"  integer                     NOT NULL DEFAULT 0,
                "OutputTokens" integer                     NOT NULL DEFAULT 0,
                "CostUsd"      numeric                     NOT NULL DEFAULT 0,
                "CreatedAt"    timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ChatMessages_ChatSessions_SessionId"
                    FOREIGN KEY ("SessionId") REFERENCES "ChatSessions" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_ChatMessages_SessionId_CreatedAt" ON "ChatMessages" ("SessionId", "CreatedAt");

            CREATE TABLE IF NOT EXISTS "Feedbacks" (
                "Id"        bigint GENERATED BY DEFAULT AS IDENTITY,
                "MessageId" uuid,
                "TenantId"  character varying(100)      NOT NULL,
                "UserId"    uuid,
                "Rating"    integer                     NOT NULL,
                "Comment"   text,
                "CreatedAt" timestamp with time zone    NOT NULL,
                CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_Feedbacks_TenantId"  ON "Feedbacks" ("TenantId");
            CREATE INDEX IF NOT EXISTS "IX_Feedbacks_CreatedAt" ON "Feedbacks" ("CreatedAt");
            """);
    }

    public static async Task SeedAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var db     = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var hasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();
        var config = scope.ServiceProvider.GetRequiredService<IConfiguration>();

        await EnsureSchemaAsync(db);

        var email    = config["Admin:Email"]    ?? "admin@example.com";
        var password = config["Admin:Password"] ?? "Admin1234!";

        if (!await db.Users.AnyAsync(u => u.Role == Role.Admin))
        {
            db.Users.Add(new User
            {
                Email        = email.ToLowerInvariant(),
                PasswordHash = hasher.Hash(password),
                Role         = Role.Admin,
                DisplayName  = "Platform Admin",
                TenantId     = null,
                IsActive     = true,
            });
            await db.SaveChangesAsync();
        }
    }
}
